require("rami.options")
require("rami.keymaps")
require("rami.plugins")
require("rami.colorscheme")
require("rami.cmp")
require("rami.lsp")
require("rami.telescope")
require("rami.treesitter")
require("rami.comment")
require("rami.gitsigns")
require("rami.nvim-tree")
require("rami.bufferline")
require("rami.null-ls")
require("rami.toggleterm")
require("rami.autopairs")
require("rami.better-escape")

